name: gridding
favicon: null
layout_spectrum: 0.5969461435452104
typography_spectrum: 0.9381872806698084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6694356019143015
  lightness: 0.14580390509217978
  saturation: 0.9172412150073797
  rhythmicContrast: 0.8110987672116607
purpose: []
